name: 'GitHub Action for Zapier'
author: 'Fullbound'
description: 'Wraps the zapier-platform-cli CLI to enable common commands.'
branding:
  icon: 'package'
  color: 'gray-dark'
runs:
  using: 'docker'
  image: 'docker://driphireweb/zapier-action:latest'
